id: D48C5A7BE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:50:26+00:00'
last_modified: '2022-05-30T04:39:35.445974+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    bebd:
      image_group_id: I1PD95942
      title: ཚད་མ་རྣམ་པར་ངེས་པ།
      total_pages: 1198
      order: 97
      base_file: bebd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
