id: PDBC9C67B
initial_creation_type: ocr
source_metadata:
  volumes:
    91bac901051e41988b9962f5e2e2ef0d:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མ་རྣམ་པར་ངེས་པ།
      total_pages: 1198
      volume_number: 97
